name: Setup Kosli CLI
description: 'Wrapper for kosli-dev/setup-cli-action'

inputs:
  version:
    description: The version of the Kosli CLI to setup
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Setup Kosli CLI
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: kosli-dev/setup-cli-action@v5
      with:
        version: ${{ inputs.version }}
